name: Publish snap

on:
  push:
    branches:
      - '[0-9].[0-9]+'
      - main
      - master
  workflow_dispatch:

jobs:
  publish:
    uses: agileshaw/bootstack-actions/.github/workflows/snap-release.yaml@snap-build-release
    secrets: inherit
    with:
      python-version-unit: "['3.8', '3.10']"
      python-version-func: "3.10"
      tox-version: "<4"
      snapcraft: true
      commands: "['make functional']"
      # Channel should be one or a (comma-separated) list of <track>/<risk-level>
      # We use the "latest" track for the default branch, otherwise use versioned branch name as the track name
      # The risk level we want to release to is "edge"
      channel: ${{ contains(fromJSON('["main", "master"]'), github.ref_name) && 'latest' || github.ref_name }}/edge
