name: SonarCloud
on:
  workflow_run:
    workflows: 
      - PR workflow running lint checkers, unit and functional tests
    types: [completed]

jobs:
  sonarcloud:
    uses: agileshaw/bootstack-actions/.github/workflows/sonar.yaml@fix-sonar
    secrets: inherit
    if: github.event.workflow_run.conclusion == 'success'
    with:
      workflow-name: PR workflow running lint checkers, unit and functional tests
